config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators
  resources :companies do
    resources :invitations, shallow: true
  end
  resources :companies
  resources :administrators
  resources :users

  devise_for :administrators, skip: [ :sessions, :passwords, :registrations, :confirmations, :unlocks ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "administrators#index"
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :company
  belongs_to :user
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_company, only: [:index, :new, :create]
  before_action :set_invitation, only: [:show, :edit, :update, :destroy]

  def index
    @invitations = Invitation.all

    if params[:name].present?
      @invitations = @invitations.joins(:user)
                                .where("users.name ILIKE ? OR users.email ILIKE ?", "%#{params[:name]}%", "%#{params[:name]}%")
    end

    if params[:company_id].present?
      @invitations = @invitations.where(company_id: params[:company_id])
    end

    if params[:start_date].present? && params[:end_date].present?
      begin
        start_date = Date.parse(params[:start_date])
        end_date = Date.parse(params[:end_date])
        @invitations = @invitations.where(created_at: start_date.beginning_of_day..end_date.end_of_day)
      rescue ArgumentError
        flash.now[:alert] = "Datas inválidas."
      end
    end

    @invitations = @invitations.where(active: true)

    @invitations = @invitations.order(created_at: :desc)
  end

  def show
  end

  def new
    @company = Company.find(params[:company_id])
    @invitation = @company.invitations.build
  end

  def edit
  end

  def create
    @invitation = Invitation.new(invitation_params)

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to @invitation, notice: "Invitation was successfully created." }
        format.json { render :show, status: :created, location: @invitation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @invitation.update(invitation_params)
        format.html { redirect_to @invitation, notice: "Invitation was successfully updated." }
        format.json { render :show, status: :ok, location: @invitation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @invitation.destroy!

    respond_to do |format|
      format.html { redirect_to invitations_path, status: :see_other, notice: "Invitation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_company
    @company = Company.find(params[:company_id])
  end

  def set_invitation
    @invitation = Invitation.find(params[:id])
  end

  def invitation_params
    params.require(:invitation).permit(:invitee_name, :invitee_email, :active, :company_id, :user_id)
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_with(model: [@company, invitation], class: "contents") do |form| %>
  <% if invitation.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>
      <ul class="list-disc ml-6">
        <% invitation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_id, "User" %>
    <%= form.collection_select :user_id, User.all, :id, :name, prompt: "Select a User", class: "block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :active %>
    <%= form.checkbox :active, class: ["block shadow-sm rounded-md border outline-hidden mt-2 h-5 w-5", {"border-gray-400 focus:outline-blue-600": invitation.errors[:active].none?, "border-red-400 focus:outline-red-600": invitation.errors[:active].any?}] %>
  </div>

  <% if invitation.new_record? %>
    <%= form.hidden_field :company_id, value: @company.id %>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/invitations/_invitation.html.erb
<div id="<%= dom_id invitation %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Invitee name:</strong>
    <%= invitation.user.name %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Invitee email:</strong>
    <%= invitation.user.email %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Active:</strong>
    <%= invitation.active %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Company:</strong>
    <%= invitation.company_id %>
  </p>
</div>

app/views/invitations/edit.html.erb
<% content_for :title, "Editing invitation" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing invitation</h1>

  <%= render "form", invitation: @invitation %>

  <%= link_to "Show this invitation", @invitation, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to invitations", company_invitations_path(@invitation.company), class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/invitations/index.html.erb
<% content_for :title, "Invitations" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <%= form_with url: company_invitations_path(@company), method: :get, local: true, class: "mb-4" do |f| %>
    <div class="flex flex-wrap gap-4">
      <div>
        <%= f.label :name, "Nome" %>
        <%= f.text_field :name, value: params[:name], class: "border px-2 py-1" %>
      </div>
      <div>
        <%= f.label :company_id, "Empresa" %>
        <%= f.select :company_id, options_from_collection_for_select(Company.all, :id, :name, params[:company_id]), { include_blank: "Selecione" }, class: "border px-2 py-1" %>
      </div>
      <div>
        <%= f.label :start_date, "Data Inicial" %>
        <%= f.date_field :start_date, value: params[:start_date], class: "border px-2 py-1" %>
      </div>
      <div>
        <%= f.label :end_date, "Data Final" %>
        <%= f.date_field :end_date, value: params[:end_date], class: "border px-2 py-1" %>
      </div>
      <div class="self-end">
        <%= f.submit "Filtrar", class: "bg-blue-500 text-white px-4 py-2 rounded" %>
      </div>
    </div>
  <% end %>

  <div id="invitations" class="min-w-full">
    <% if @invitations.any? %>
      <% @invitations.each do |invitation| %>
        <%= render invitation %>
        <p>
          <%= link_to "Show this invitation", invitation, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
        </p>
      <% end %>
    <% else %>
      <p class="text-center my-10">No invitations found.</p>
    <% end %>
  </div>
</div>

app/views/invitations/new.html.erb
<% content_for :title, "New invitation" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New invitation</h1>

  <%= render "form", invitation: @invitation %>

  <%= link_to "Back to invitations", company_invitations_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/invitations/show.html.erb
<% content_for :title, "Showing invitation" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing invitation</h1>

  <%= render @invitation %>

  <%= link_to "Edit this invitation", edit_invitation_path(@invitation), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to invitations", company_invitations_path(@invitation.company), class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this invitation", @invitation, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>