config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators
  resources :companies do
    resources :invitations, shallow: true
  end
  resources :companies
  resources :administrators
  resources :users

  devise_for :administrators, skip: [ :sessions, :passwords, :registrations, :confirmations, :unlocks ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "administrators#index"
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  # has_secure_password
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :set_administrator, only: %i[ show edit update destroy ]

  def index
    @administrators = Administrator.all
  end

  def show
  end

  def new
    @administrator = Administrator.new
  end

  def edit
  end

  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, notice: "Administrator was successfully created." }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to @administrator, notice: "Administrator was successfully updated." }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @administrator.destroy!

    respond_to do |format|
      format.html { redirect_to administrators_path, status: :see_other, notice: "Administrator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    def administrator_params
      params.require(:administrator).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_administrator.html.erb
<div id="<%= dom_id administrator %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= administrator.name %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= administrator.email %>
  </p>
</div>

app/views/administrators/_form.html.erb
<%= form_with(model: administrator, class: "contents") do |form| %>
  <% if administrator.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul class="list-disc ml-6">
        <% administrator.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: [
      "block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full",
      administrator.errors[:name].any? ? "border-red-400 focus:outline-red-600" : "border-gray-400 focus:outline-blue-600"
    ] %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: [
      "block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full",
      administrator.errors[:email].any? ? "border-red-400 focus:outline-red-600" : "border-gray-400 focus:outline-blue-600"
    ] %>
  </div>

  <div class="my-5">
    <%= form.label :password %>
    <%= form.password_field :password, autocomplete: "new-password", class: [
      "block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full",
      administrator.errors[:password].any? ? "border-red-400 focus:outline-red-600" : "border-gray-400 focus:outline-blue-600"
    ] %>
  </div>

  <div class="my-5">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, autocomplete: "new-password", class: [
      "block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full",
      administrator.errors[:password_confirmation].any? ? "border-red-400 focus:outline-red-600" : "border-gray-400 focus:outline-blue-600"
    ] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/administrators/edit.html.erb
<% content_for :title, "Editing administrator" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing administrator</h1>

  <%= render "form", administrator: @administrator %>

  <%= link_to "Show this administrator", @administrator, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to administrators", administrators_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/administrators/index.html.erb
<% content_for :title, "Administrators" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Administrators</h1>
    <%= link_to "New administrator", new_administrator_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="administrators" class="min-w-full">
    <% if @administrators.any? %>
      <% @administrators.each do |administrator| %>
        <%= render administrator %>
        <p>
          <%= link_to "Show this administrator", administrator, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
        </p>
      <% end %>
    <% else %>
      <p class="text-center my-10">No administrators found.</p>
    <% end %>
  </div>
</div>

app/views/administrators/new.html.erb
<% content_for :title, "New administrator" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New administrator</h1>

  <%= render "form", administrator: @administrator %>

  <%= link_to "Back to administrators", administrators_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/administrators/show.html.erb
<% content_for :title, "Showing administrator" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing administrator</h1>

  <%= render @administrator %>

  <%= link_to "Edit this administrator", edit_administrator_path(@administrator), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to administrators", administrators_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this administrator", @administrator, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>